# Generated by Django 5.1.6 on 2025-02-22 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'verbose_name': 'Klassenstufe',
                'verbose_name_plural': 'Klassenstufen',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.CreateModel(
            name='StundentDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dateiname', max_length=50)),
                ('file', models.FileField(upload_to='accounts/management/commands/tmp/')),
            ],
            options={
                'verbose_name': 'Schülerliste Importieren ',
                'verbose_name_plural': 'Schülerlisten Importieren',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abkuerzung', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_choice', models.CharField(choices=[('A', 'A-Woche'), ('B', 'B-Woche')], default='A', max_length=7)),
            ],
            options={
                'verbose_name': 'Wochenoption',
                'verbose_name_plural': 'Wochenoptionen',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('l', 'l')], max_length=1)),
                ('schueleranzahl', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('schueler_in_class', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('bezeichnung', models.CharField(blank=True, max_length=20)),
                ('grade', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.grade')),
            ],
            options={
                'verbose_name': 'Klasse',
                'verbose_name_plural': 'Klassen',
            },
        ),
        migrations.CreateModel(
            name='Subject_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochenstunden', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject')),
            ],
            options={
                'verbose_name': 'Klassenstufe-Fach-Abhänigkeit',
                'verbose_name_plural': 'Klassenstufe-Fach-Abhänigkeiten',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(through='stundenplan.Subject_Grade', to='stundenplan.grade'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=3)),
                ('subjects', models.ManyToManyField(to='stundenplan.subject')),
            ],
            options={
                'verbose_name': 'Lehrer',
                'verbose_name_plural': 'Lehrer',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('klasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stundenplan.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schüler Profile',
                'verbose_name_plural': 'Schüler Profile',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(choices=[('1', '1 Stunde'), ('2', '2 Stunde'), ('3/4', '3/4 Stunde'), ('5/6', '5/6 Stunde'), ('7/8', '7/8 Stunde')], max_length=5)),
                ('weekday', models.CharField(choices=[('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag')], max_length=2)),
                ('klasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.class')),
                ('room_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.teacher')),
                ('week_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.week')),
            ],
            options={
                'verbose_name': 'Stunde',
                'verbose_name_plural': 'Stunden',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'klasse', 'weekday', 'lesson_number'), name='unique_lesson')],
            },
        ),
    ]
