# Generated by Django 5.1.5 on 2025-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_grade',
            options={'verbose_name': 'Klassenstufe-Fach', 'verbose_name_plural': 'Klassenstufe-Fach'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.CharField(choices=[('1', '1 Stunde'), ('2', '2 Stunde'), ('3/4', '3/4 Stunde'), ('5/6', '5/6 Stunde'), ('7/8', '7/8 Stunde')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.CharField(choices=[('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag')], max_length=2, null=True),
        ),
    ]
