# Generated by Django 5.1.5 on 2025-01-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
