# Generated by Django 5.1.5 on 2025-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0002_alter_subject_grade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='faecher',
            field=models.ManyToManyField(to='stundenplan.subject'),
        ),
    ]
