# Generated by Django 5.1.5 on 2025-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0003_rename_lehrer_teacher_teached_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teached_subjects',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(through='stundenplan.Teached_Subjects', to='stundenplan.teacher'),
        ),
    ]
