# Generated by Django 5.1.5 on 2025-01-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0004_teached_subjects_subject_alter_class_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Teached_Subjects',
        ),
    ]
