# Generated by Django 5.1.5 on 2025-01-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0005_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teached_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(through='stundenplan.Teached_Subject', to='stundenplan.teacher'),
        ),
    ]
