# Generated by Django 5.1.5 on 2025-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0005_remove_class_teachers_delete_teached_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='stundenplan.teacher'),
        ),
    ]
