# Generated by Django 5.1.5 on 2025-01-21 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0006_teached_subject_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.grade'),
        ),
    ]
