# Generated by Django 5.1.5 on 2025-01-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0006_class_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
