# Generated by Django 5.1.5 on 2025-01-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0007_delete_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
