# Generated by Django 5.1.5 on 2025-01-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0007_class_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teached_Subject',
            new_name='Teacher_Class',
        ),
        migrations.CreateModel(
            name='Subject_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochenstunden', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(through='stundenplan.Subject_Grade', to='stundenplan.grade'),
        ),
    ]
