# Generated by Django 5.1.5 on 2025-01-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0008_rename_teached_subject_teacher_class_subject_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='stundenplan.subject'),
        ),
        migrations.AlterField(
            model_name='teacher_class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject'),
        ),
    ]
