# Generated by Django 5.0.7 on 2025-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0009_teacher_subjects_alter_teacher_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('weekday', models.CharField(choices=[('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag')], default='MO', max_length=2)),
            ],
        ),
    ]
