# Generated by Django 5.0.7 on 2025-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0010_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.TextField(choices=[('1', 'erste Stunde'), ('2', 'zweite Stunde'), ('3/4', '3/4 Stunde'), ('5/6', '5/6 Stunde'), ('7/8', '7/8 Stunde')]),
        ),
    ]
