# Generated by Django 5.0.7 on 2025-01-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0011_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.TextField(choices=[('1', '1 Stunde'), ('2', '2 Stunde'), ('3/4', '3/4 Stunde'), ('5/6', '5/6 Stunde'), ('7/8', '7/8 Stunde')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.CharField(choices=[('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag')], max_length=2),
        ),
    ]
