# Generated by Django 5.0.7 on 2025-01-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0012_alter_lesson_lesson_number_alter_lesson_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.class'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.CharField(choices=[('1', '1 Stunde'), ('2', '2 Stunde'), ('3/4', '3/4 Stunde'), ('5/6', '5/6 Stunde'), ('7/8', '7/8 Stunde')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('teacher', 'subject', 'klasse', 'weekday', 'lesson_number')},
        ),
    ]
