# Generated by Django 5.0.7 on 2025-01-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0014_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='grade_with_char',
            new_name='klasse',
        ),
    ]
