# Generated by Django 5.0.7 on 2025-01-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0016_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.room'),
        ),
    ]
