# Generated by Django 5.1.5 on 2025-01-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0018_remove_class_teachers_alter_grade_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='name',
        ),
    ]
