# Generated by Django 5.0.7 on 2025-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0021_alter_class_schueleranzahl_alter_grade_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'klasse', 'weekday', 'lesson_number'), name='unique_lesson'),
        ),
    ]
