# Generated by Django 5.0.7 on 2025-01-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0022_alter_lesson_unique_together_lesson_unique_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
