# Generated by Django 5.0.7 on 2025-01-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0023_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
    ]
