# Generated by Django 5.1.5 on 2025-01-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0025_rename_schoolclass_class_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
