# Generated by Django 5.1.5 on 2025-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0028_class_schueler_in_class_alter_class_schueleranzahl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='bezeichnung',
            field=models.CharField(default='<django.db.models.fields.CharField>None', max_length=3),
        ),
    ]
