# Generated by Django 5.1.5 on 2025-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0029_class_bezeichnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
