# Generated by Django 5.0.7 on 2025-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0030_alter_class_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='StundentDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='accounts/management/commands/tmp/')),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('l', 'l')], max_length=1),
        ),
    ]
