# Generated by Django 5.0.7 on 2025-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0031_stundentdataimport_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stundentdataimport',
            name='name',
            field=models.CharField(default='user_data1.csv', max_length=255),
        ),
    ]
