# Generated by Django 5.0.7 on 2025-02-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0032_stundentdataimport_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stundentdataimport',
            name='name',
        ),
        migrations.AlterField(
            model_name='class',
            name='schueleranzahl',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
