# Generated by Django 5.0.7 on 2025-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0033_remove_stundentdataimport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stundentdataimport',
            name='name',
            field=models.CharField(default='Dateiname', max_length=50),
        ),
    ]
