# Generated by Django 5.0.7 on 2025-02-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0034_stundentdataimport_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Klassenstufe', 'verbose_name_plural': 'Klassenstufen'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Raum', 'verbose_name_plural': 'Räume'},
        ),
        migrations.AlterModelOptions(
            name='stundentdataimport',
            options={'verbose_name': 'Schülerliste Importieren ', 'verbose_name_plural': 'Schülerlisten Importieren'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='subject_grade',
            options={'verbose_name': 'Klassenstufe-Fach-Abhänigkeit', 'verbose_name_plural': 'Klassenstufe-Fach-Abhänigkeiten'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Lehrer', 'verbose_name_plural': 'Lehrer'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Schüler Profile', 'verbose_name_plural': 'Schüler Profile'},
        ),
    ]
