# Generated by Django 5.1.5 on 2025-02-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0035_alter_class_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Stunde', 'verbose_name_plural': 'Stunden'},
        ),
    ]
