# Generated by Django 5.1.5 on 2025-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0036_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
