# Generated by Django 5.0.7 on 2025-02-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0037_userprofile_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_choice', models.CharField(choices=[('A', 'A-Woche'), ('B', 'B-Woche')], default='A', max_length=7)),
            ],
            options={
                'verbose_name': 'Wochenoption',
                'verbose_name_plural': 'Wochenoptionen',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.week'),
        ),
    ]
