# Generated by Django 5.1.6 on 2025-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenplan', '0038_week_lesson_week_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
