# Generated by Django 5.0.7 on 2025-02-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notentabelle', '0001_initial'),
        ('stundenplan', '0035_alter_class_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stundenplan.subject'),
            preserve_default=False,
        ),
    ]
