# Generated by Django 5.0.7 on 2025-02-12 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notentabelle', '0003_remove_mark_mark_mark_klausur_mark_note_1_and_more'),
        ('stundenplan', '0035_alter_class_options_alter_grade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject'),
        ),
    ]
