# Generated by Django 5.0.7 on 2025-02-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notentabelle', '0004_mark_unique_user_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
    ]
