# Generated by Django 5.1.5 on 2025-02-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notentabelle', '0005_alter_mark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Noten'},
        ),
    ]
